Music/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView


from . import views


urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='Home'),
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    url(r'^(?P<pk>[0-9]+)/$',views.PlayerView.as_view(), name='player'),
    url(r'album/add/$', views.AlbumCreate.as_view(),name='album-add'),
    url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(),name='album-update'),
    url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(),name='album-delete'),
    url(r'album/(?P<pk>[0-9]+)/song/$',views.SongAdd.as_view(),name='song-add'),
    url(r'^song/(?P<pk>[0-9]+)/delete/$', views.SongDelete.as_view(), name='song-delete'),
url(r'^favicon\.ico$',RedirectView.as_view(url='/static/images/favicon.ico')),
]

Musify/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('Music.urls')),
    ]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Music/models.py
from django.db import models
from django.urls import reverse

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField(upload_to="images/")

    def get_absolute_url(self):
        return reverse('player', kwargs={'pk':self.pk})

    def __str__(self):
        return self.album_title + ' - ' + self.artist

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    song_file = models.FileField(upload_to="songs/")
    is_favorite = models.BooleanField(default=False)




    def __str__(self):
        return self.song_title

    def get_absolute_url(self):
        return reverse('player', kwargs={'pk': self.pk})

Music/forms.py
from django.contrib.auth.models import  User
from django import forms

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model=User
        fields=['username','email','password']

Music/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login
from .models import Album,Song
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy,reverse
from django.views.generic import View
from .forms import UserForm

class HomeView(generic.ListView):
    template_name = 'Home.html'

    def get_queryset(self):
        '''
        if request.method == "GET":
            pass
        else:
            return Album.objects.all()
        '''
        return Album.objects.all()

class PlayerView(generic.DetailView):
    model=Album
    template_name='player.html'

class AlbumCreate(CreateView):
    model=Album
    template_name='album_form.html'
    fields = ['artist','album_title','genre','album_logo']

class AlbumUpdate(UpdateView):
    model=Album
    template_name='album_form.html'
    fields = ['artist','album_title','genre','album_logo']

class AlbumDelete(DeleteView):
    model=Album
    success_url=reverse_lazy('Home')

class UserFormView(View):
    form_class=UserForm
    template_name='registration_form.html'

    def get(self,request):
        form=self.form_class(None)
        return render(request,self.template_name,{'form':form})

    def post(self,request):
        form=self.form_class(request.POST)

        if form.is_valid():
            user=form.save(commit=False)

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user=authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request,user)
                    return redirect('Home')
        return render(request,self.template_name,{'form':form})

class SongAdd(CreateView):
    model = Song
    template_name = 'song_form.html'
    fields = ['song_title','song_file']

    def get_success_url(self):
        return reverse("player", kwargs={'pk': self.kwargs['pk']})



    def form_valid(self, form):
        album = Album.objects.get(pk=self.kwargs['pk'])
        form.instance.album = album
        return super(SongAdd, self).form_valid(form)

class SongDelete(DeleteView):
    model=Song


    #def post(self,request):
    #print(self.kwargs['pk'])
    #print(request.POST["song_album_id"])
    success_url = reverse_lazy('Home')
    #def get_success_url(self):
        #print(request.POST["song_album_id"])
        #success_url = reverse_lazy('Home')
        #print("this is the printed primary key",self.kwargs['pk'])
        #return reverse("player", kwargs={'pk': self.kwargs['pk']})

templates/Home.html
<!DOCTYPE html>
<html lang="en">
<head>

    <style>
    img{
        max-width: 200px;
        max-height: 200px;
        }

    </style>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>Musify</title>
</head>
<body style="background-color: #000000;">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
  <a class="navbar-brand" href="{%url 'Home'%}" ><button type="button" class="btn btn-primary"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-music-note" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path d="M9 13c0 1.105-1.12 2-2.5 2S4 14.105 4 13s1.12-2 2.5-2 2.5.895 2.5 2z"></path>
  <path fill-rule="evenodd" d="M9 3v10H8V3h1z"></path>
  <path d="M8 2.82a1 1 0 0 1 .804-.98l3-.6A1 1 0 0 1 13 2.22V4L8 5V2.82z"></path>
</svg> Musify</button></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="nav navbar-nav">




        <li class="nav-item" style="position: absolute;left: 80%;top:15%;">
            <a href="{%url 'album-add'%}">
        <button type="button" class="btn btn-success" >Add Album</button>
            </a>
      </li>

        <li class="nav-item" style="position: absolute;left: 90%;top:15%;">
        <a href="{%url 'register'%}">
            <button type="button" class="btn btn-danger">LogOut</button>
        </a>
      </li>



    </ul>


  </div>
</nav>
    <div class="card-group" style="overflow: auto;">
    {% if object_list %}
        {% for album in object_list %}
        <div class="row">
            <div class="container" style="background-color: 16161;">
                <div class="card" style="width: 18rem; height: 25rem; margin: 1rem">
            <img src="{{album.album_logo.url}}" class="card-img-top" alt="..." style="width: 100%; max-width: 100%;">
            <div class="card-body">
              <h5 class="card-title">{{album.album_title}}</h5>
              <p class="card-text" style="height: 5rem; width: 12rem; overflow: auto;">{{album.artist}}<br>{{album.genre}}</p>
              <a href="{% url 'player' album.id %}" class="btn btn-primary">{{album.album_title}}</a>
              <form action="{% url 'album-delete' album.id %}" method="post" style="display: inline; z-index:3;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-danger">
                                    Delete
                                </button>
              </form>
                  <form action="{% url 'album-update' album.id %}" method="get" style="display: inline; z-index:3;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-success">
                                    Edit
                                </button>
                            </form>



            </div>
            </div>
            </div>
        </div>
        {% endfor %}

    {% else %}
        <h3>You don't have any albums</h3>
    {% endif %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  </body>
<script type="text/javascript">
  var slider=document.getElementById("range");
  slider.addEventListener("mousemove", function(){
      var x=slider.value;
      var color="linear-gradient (90deg, #007bff' +x+ '%, white'+x+'%')";
        slider.style.background=color;
    }
</script>
</html>

templates/album_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Title</title>
</head>
<body style="background-color:black; color:white;">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
  <a class="navbar-brand" href="{%url 'Home'%}" ><button type="button" class="btn btn-primary"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-music-note" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path d="M9 13c0 1.105-1.12 2-2.5 2S4 14.105 4 13s1.12-2 2.5-2 2.5.895 2.5 2z"></path>
  <path fill-rule="evenodd" d="M9 3v10H8V3h1z"></path>
  <path d="M8 2.82a1 1 0 0 1 .804-.98l3-.6A1 1 0 0 1 13 2.22V4L8 5V2.82z"></path>
</svg> Musify</button></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">



        <li class="nav-item" style="position: absolute;left: 90%; top:15%; font-weight: bold;">
        <button type="button" class="btn btn-danger">LogOut</button>
      </li>



    </ul>


  </div>
</nav>
<div class="container-fluid">
<div class="row">
    <div class="col-sm-12 col-md-7">
        <div class="panel panel-default">
        <div class="panel-body">
<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
    {%csrf_token%}
    {%include 'form-template.html'%}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </div>
</form>
        </div>
    </div>
</div>
</div>
</div>




  <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>

templates/form-template.html
{%for field in form%}
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{field.errors}}</span>

    </div>
    <label class="control-label col-sm-2">{{field.label_tag}}</label>
    <div class="col-sm-10">{{field}}</div>
</div>
{%endfor%}

templates/player.html
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
<style>
.playpause label { display: block; box-sizing: border-box; width: 0; height: 25px; border-color: transparent transparent transparent #ffffff; transition: 100ms all ease; cursor: pointer; border-style: double; border-width: 0px 0 0px 25px;} .playpause input[type="checkbox"] { visibility: hidden; } .playpause input[type="checkbox"]:checked + label { border-style: solid; border-width: 13px 0 13px 25px; }
.playpause{

    border-radius:50%;
    height:55px;
    width:55px;
    text-align:center;
    position:relative;
    background-color:#007bff;
}
label{
    position:absolute ;
    left:15px;
    top:15px;
}


#majorplayerslider{
		  left:0%;
          position: absolute;
          z-index: 1;
          width: 100%;
          -webkit-appearance: none;
          height: 5px;
          background: white;
          outline: none;
          opacity: 0.7;
          -webkit-transition:0.2s;
          transition: opacity 0.2s;
          border-radius: 200px;
          margin:0px;
          top:0px;



        }

 .song_row:hover{
 opacity: 0.6
 }

    #mainaudioplayer{
    visibility : hidden;
    }
}
</style>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Sofia' rel='stylesheet'>
</head>
<body>
<div style="position:absolute; margin:0px; top:00%; left:00% ;height: 100%; width:100%; background-color: black; overflow-y: hidden; z-index: 0">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
  <a class="navbar-brand" href="{%url 'Home'%}" ><button type="button" class="btn btn-primary"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-music-note" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path d="M9 13c0 1.105-1.12 2-2.5 2S4 14.105 4 13s1.12-2 2.5-2 2.5.895 2.5 2z"></path>
  <path fill-rule="evenodd" d="M9 3v10H8V3h1z"></path>
  <path d="M8 2.82a1 1 0 0 1 .804-.98l3-.6A1 1 0 0 1 13 2.22V4L8 5V2.82z"></path>
</svg> Musify</button></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <a class="nav-item" style="position: absolute;left: 90%;" href="{%url 'register'%}">
            <button type="button" class="btn btn-danger">LogOut</button>
        </a>
  </div>
</nav>
<div   style="position:absolute; margin:20px; top:10%; left:3%;height:200px;width:200px;">
	<img src="{{album.album_logo.url}}" class="img-responsive" style="height: 100%;width: 100%;">

<div style="position: absolute; color:white; z-index: 1;width:80%;
  top: 10%;
  left: 130%">Album<br><h3><b>{{album.album_title}}</b></h3>Artist<br><h3><b>{{album.artist}}</b></h3>
</div>
</div>

<form action="{% url 'song-add' album.id %}" method="get" style="display: inline; z-index:3; margin-left: 1245px;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-success" style="margin: 10px;">
                                    AddSong
                                </button>
                            </form>


<div class="container-fluid overflow-auto" style="position: fixed; z-index: 2; top: 430px; left: 50%; height:270px; transform: translate(-50%, -50%); margin: 5px; ">

    <table class="table table-dark">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th class="" scope="col">Title</th>
            </tr>
          </thead>
             <tbody>

                {% for song in album.song_set.all %}
                     <tr class="song_row" id="{{song.pk}}"  style="background-color:black;"  onclick="song_row_click(this)">
                      <th scope="row">{{forloop.counter}}
                      </th>
                      <td>{{song.song_title}}</td>
                         <td ><audio controls style="visibility:hidden;">
                        <source class="mini_player" id="{{song.pk}}_id_song" src="{{song.song_file.url}}" type="audio/mpeg"/>
                    </audio></td>
                       <td>
                        <form action="{% url 'song-delete' song.pk %}" method="post" style="display: inline; z-index:3;">
                                {% csrf_token %}
                                <input type="hidden" name="song_id" value="{{ song.pk }}" />
                                <input type="hidden" name="song_album_id" value="{{ song.album }}" />
                                <button type="submit" class="btn btn-success">
                                    DeleteSong
                                </button>
                        </form>
                       </td>
                    </tr>
                {% endfor %}
             </tbody>
    </table>

    </div>

    <div id="main_player_div" style="position:fixed; top:700px; left:0px; visibility: visible;">

    </div>

<div class="bg-dark" id="majorplayer" style="position:fixed; margin:0px; top:670px ;left:0px ;height: 80px; width:100%; visibility: hidden;">
 <form class="bg-dark" >
	  <input type="range" min="1" max="101" value="1" class="slider" id="majorplayerslider"/>
	   <div id="wrapper" style="position:absolute ;left:48%;top: 15%;">
	   	<div class="playpause">

	          <input type="checkbox" value="None" id="playpause" name="check" onclick="statechange()"/>
	          <label for="playpause">

	          </label>
	  	</div>
	   </div>

 </form>
</div>
</div>
<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
<script type="text/javascript">



  var slider=document.getElementById("majorplayerslider");
  //var x;
  slider.addEventListener("click", function(){
      var x = parseInt(slider.value);
      //console.log(x);

      //var color = "linear-gradient(90deg, #007bff " + x.toString() +"%,#ffffff "+ (100-x).toString() +"%)";
      //var color = "blue";
      //alert(color);
      //slider.style.background = color;

      var songduration = document.getElementById("mainaudioplayer");
      //alert(songduration.currentTime);
      //console.log(songduration.duration);
      songduration.currentTime = parseFloat(x).toFixed(4);
      console.log(parseFloat(x).toFixed(4));
      console.log(songduration.currentTime);
      console.log(document.getElementById("mainaudioplayer"));
      //slider.value=songduration.currentTime;

    }
   )


    function statechange()
    {
       //alert("working");
       var playpausebutton = document.getElementById("playpause");
       //alert(playpausebutton.checked);

       if (playpausebutton.checked == false)
       {
            //alert("play");
            document.getElementById('mainaudioplayer').play();
       }
       else
       {
            //alert("pause");
            document.getElementById('mainaudioplayer').pause();
       }

       setTimeout(function(){
        var songduration = document.getElementById("mainaudioplayer").duration;
        var slider = document.getElementById("majorplayerslider");
        //console.log(parseInt(songduration));
        slider.max = parseInt(songduration) + 1;
        }, 1000);

    }



    function song_row_click(obj)
    {   var song_id = obj.id;
        var source_id = song_id + "_id_song";
        var song_src = document.getElementById(source_id).src;
        //alert(song_src);

        main_player_div_inner_stuff = '<audio id="mainaudioplayer" controls > <source id="main_player" src="'+ song_src +'" type="audio/mpeg" /> </audio>';
        //var x = document.getElementById(main_player_div); //.innerHTML = "hello rohan";
        var x = $("#main_player_div").html(main_player_div_inner_stuff);
        //alert(x);

        var majorplayer = document.getElementById("majorplayer");
        //alert(majorplayer.value);
        majorplayer.style.visibility = "visible";
        statechange();



        var slideaoturunner= setInterval(function( ){
                             var songduration = document.getElementById("mainaudioplayer").duration;
                             var slider=document.getElementById("majorplayerslider");
                             var currenttiming = document.getElementById("mainaudioplayer").currentTime;
                             //(songduration.currentTime);
                             slider.value = parseInt(currenttiming);
                             //console.log(currenttiming);
                             //console.log(songduration);
                             leftpercent = parseInt(parseInt(currenttiming)/parseInt(songduration)*100);
                             //console.log(leftpercent);
                             var color = "linear-gradient( to right,#007bff, #007bff " + leftpercent.toString() +"%,#ffffff "+ leftpercent.toString() +"%)";
                             //console.log(color);
                             slider.style.background = color;
                             }, 500);
                            }


</script>
  </html>

templates/registration_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Registration</title>
</head>
<body style="background-color:black; color:white;">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
  <a class="navbar-brand" href="{%url 'Home'%}" ><button type="button" class="btn btn-primary"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-music-note" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path d="M9 13c0 1.105-1.12 2-2.5 2S4 14.105 4 13s1.12-2 2.5-2 2.5.895 2.5 2z"></path>
  <path fill-rule="evenodd" d="M9 3v10H8V3h1z"></path>
  <path d="M8 2.82a1 1 0 0 1 .804-.98l3-.6A1 1 0 0 1 13 2.22V4L8 5V2.82z"></path>
</svg> Musify</button></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

</nav>
<div class="container-fluid">
<div class="row">
    <div class="col-sm-12 col-md-7">
        <div class="panel panel-default">
        <div class="panel-body">
<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
    {%csrf_token%}
    {%include 'form-template.html'%}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </div>
</form>
        </div>
    </div>
</div>
</div>
</div>